language: python
dist: bionic
python: "3.8"
sudo: required

before_install:
  - sudo apt-get -y install cmake libboost-all-dev libsdl2-dev libfreetype6-dev libgl1-mesa-dev libglu1-mesa-dev libpng-dev libjpeg-dev libbz2-dev libfluidsynth-dev libgme-dev libopenal-dev zlib1g-dev timidity tar nasm

install:
  - pip install -r requirements.txt

script:
  - pytest